name: Recurring system tests for :server module
permissions:
  issues: write
on:
  workflow_dispatch:
  schedule:
    - cron: "30 * * * *"
jobs:
  system_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 23

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Local system test
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: ./gradlew :server:systemTest :server:createIssueOnLocalFailure :server:closeIssueOnLocalSuccess --continue --stacktrace

      - name: Remote system test
        if: ${{ !cancelled() }} # If local system test fails, we will run remote test anyway
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: ./gradlew :server:systemTest :server:createIssueOnRemoteFailure :server:closeIssueOnRemoteSuccess --continue --stacktrace